### ISSUE TITLE
ignoreHTTPSErrors not working?

### ISSUE THREAD

**Issue by xclnky** [johnrichardrinehart/PuppeteerScraper#3]
/fetch?url=https://mazoondairy.com/
/fetch?url=https://null-bar.es
/fetch?url=https://teaamohamilton.com/
/fetch?url=https://www.erborian.ru/
/fetch?url=https://beyondactivewearph.com
/fetch?url=https://www.moosacosmetix.co.za/shop/

These websites have certificate problem. But they are expected to work if we ignoreHTTPSErrors in puppeteer.

**Comment by johnrichardrinehart** [comment]
On it.

**Comment by johnrichardrinehart** [comment]
Fixed with 98cc5e9af1290d171e02374d3afefaf299c8767c.
